# Generated by Django 3.1.6 on 2022-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Automobiles', models.CharField(choices=[('Bus', 'Bus'), ('Car', 'Car'), ('Auto', 'Auto'), ('Bike', 'Bike')], max_length=100)),
            ],
        ),
    ]
