# Generated by Django 3.1.6 on 2022-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220115_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Automobiles', models.CharField(choices=[('Bus', 'Bus'), ('Car', 'Car'), ('Auto', 'Auto'), ('Bike', 'Bike')], default='Bus', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Automobiles',
        ),
    ]
