# Generated by Django 3.1.6 on 2022-01-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20220115_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
